export {default as ILiveInYou} from  '../../assets/images/ILiveInYou.svg'
export {default as nextLevel} from  '../../assets/images/next-level official video.jpeg'
export {default as youtubeIcon} from  '../../assets/images/youtube icon.png'
export {default as whatsAppIcon} from  '../../assets/images/whatsapp icon.png'
export {default as faceBookIcon} from  '../../assets/images/facbook icon.png'
export {default as linkedInIcon} from  '../../assets/images/linkedIn_icon-removebg-preview.png'
export {default as PraiseMAchineMusicLogo} from  '../../assets/images/PraiseMachineMusicLogo.svg'
export {default as kabiyesiOfficialImage} from  '../../assets/images/Kabiyesi official image.jpg'
export {default as manOfWar} from  '../../assets/images/manOfWar.svg'

